#Write a program to input eight numbers from the user and display all the unique numbers (once)
s=set()
s1= input("enter the number:")
s.add(s1)
s2= input("enter the number:")
s.add(s2)
s3= input("enter the number:")
s.add(s3)
s4= input("enter the number:")
s.add(s4)
s5= input("enter the number:")
s.add(s5)
s6= input("enter the number:")
s.add(s6)
s7= input("enter the number:")
s.add(s7)
s8= input("enter the number:")
s.add(s8)
print(s,type(s)) #{'1', '4', '3', '5', '12'} <class 'set'>

